---
title: Gorkha Earthquake In Retrospect - Lessons In Diplomacy, Preparedness, & Morality
author: Biju Ale
date: 2020-10-02
tags: ["Journal"]
---

<TOC headings={props.headings} />

# Tectonic Tragedy

Two decades ago, the British seismologist Roger Bilham expounded on the inevitable “[next great quake](https://www.himalmag.com/the-next-great-earthquake/)” in the Himalayas. On April 25, 2015, a [7.8 magnitude earthquake](https://www.himalmag.com/subterranean-shifts-science-nepal-gorkha-earthquake/) (and the subsequent 7.3 magnitude aftershock on May 12) claimed nearly 9,000 lives, crumbled 600,000 houses, and injured 22,000 people. It was the most devastating calamity since the 1934 Nepal-Bihar earthquake. Much of the likes of Bilham’s prognosis was fulfilled; despite all the tragedy, the 2015 earthquake was not the anticipated “big one:” the great quake still lurks in the future, ready to unleash havoc somewhere in western Nepal. The good news is that the lessons learned from 2015 can significantly mitigate losses from the impending calamity.

Within 48 hours of the tremor, the United Nations prepared its global flash appeal for Nepal. State, civil and military groups, and national and international humanitarian organizations sprang into action in rescue missions. The early response was coordinated by the United Nations Office for the Coordination of Humanitarian Affairs under the technical cluster system. I was [part](https://logcluster.org/document/meeting-minutes-gorkha-13-august-2015) of the response, with [DanChurchAid (DCA)](https://www.danchurchaid.org/about-dca) from May to November, as DCA’s logistics aide deployed in Gorkha, coordinating our humanitarian operation [with](https://logcluster.org/sites/default/files/logistics_cluster_nepal_gorkha_meeting_minutes_150617.pdf) the logs cluster.

This article will delineate several imperatives for Nepal across two domains, domestic and foreign, set in the backdrop of the earthquake. Regarding domestic affairs, I begin by assessing the socio-economic nature of the earthquake’s impact. Then, I discuss an emergent moral callousness of nationalist urbanites ensuing from the iconization of a toppled monument. I likewise draw attention to the serious threat of casteism to aid equality and human rights in the dominant Hindu society. On the foreign affairs front, I examine myriad episodes of opportunist disaster politics, subtle and explicit, that played-out during the crisis; I inspect the Indian response, their journalism, and Nepal’s deflection of a British grant. Subsequently, I highlight why Nepal needs an institutional intelligentsia sensitive to humanitarian scenarios. In summary, I propose a cumulative case for the need for a cross-cutting moral underpinning that strengthens Nepal’s preparedness, risk reduction, and disaster resilience.

# At Ground Zero

The name “Nepal” can evoke nirvanic imagery of a serene realm nestled in the Himalayas of majestic mountains, along with exotic valleys and plains harboring an ethnic mosaic. Although this static depiction captures truth to some extent, there is more to the whole truth. In fact, Nepal was rebuilding differently before the Gorkha earthquake. For centuries, across much of modern history, Nepal had been an authoritarian state where its people have been struggling for access to education, health, progressive social mobility, inclusiveness, equality, and economic independence. The 1950-51 revolution uprooted the totalitarian _Rana_ monarchy and ushered in, for the first time, a polity with a party system. After many successive failed governments, in 2007, the country began the radical transition from a 240-year old Hindu monarchy to a secular democratic republic. This transition was followed by the second ‘people’s movement’ and the permanent ceasefire of a decade-long civil war. Against this backdrop, the devastating tremor jolted the country.

Birds of Kathmandu, sensing grave danger, instantly ascended to flight, before the temples they were resting on [crumbled](https://www-staging.nationalgeographic.com/news/2015/04/150425-nepal-earthquake-faults-geology-science/). The capital city of deities and temples was [flung](https://www.theguardian.com/world/2015/apr/28/nepal-earthquake-moves-kathmandu-but-everest-height-unchanged-experts) 10 feet southward. Most of the pagodas, historical monuments, and the shrines of the valley’s World Heritage [sites](https://www.nationalgeographic.com/news/2015/04/150427-nepal-earthquake-damage-temples-buddhism-hinduism-world-heritage-monuments-unesco/) turned into [heaps](https://www.youtube.com/watch?v=Yyhh98NDLNs) of crushed planks and bricks. One hundred fifty miles to the east, in the Mount Everest base camp, twenty-one mountaineers aiming for the summit were cut short in the [fatal avalanche](https://www.nytimes.com/2015/04/27/world/asia/katmandu-nepal-fear-loss-and-devastation.html?emc=edit_th_20150427&nl=todaysheadlines&nlid=58413496&_r=0) triggered by the earthquake. Panicked families streamed out into the open spaces, many unable to make it to safety.

The tremor originated from the _Barpak_ region of the Gorkha district and propagated eastward. [Fourteen](https://reliefweb.int/report/nepal/gorkha-earthquake-18-moderately-affected-districts) out of the then 75 districts of the country were the most severely affected, while others remained largely unscathed. The disproportionate structural damage between the urban and the rural geography immediately evinced socio-economic disparity in Nepal. The Nepalese house is commonly classified in the lingua franca as either _pakki,_ literally meaning ‘firm and concrete’ or _kacchi,_ meaning ‘raw and muddy.’ Virtually all the homes collapsed were of the latter kind, which [represents](https://culanth.org/fieldsights/we-need-an-even-bigger-one-disasters-of-inequality-in-postquake-kathmandu-valley) 80 percent of Nepal’s housings that span the bucolic hills. Only 15 percent of the private homes were [destroyed](https://culanth.org/fieldsights/we-need-an-even-bigger-one-disasters-of-inequality-in-postquake-kathmandu-valley) in Kathmandu valley, despite its short proximity with the epicenter. Most of them were buildings belonging to elite landlords, who had long been illegally extending their structures beyond the constraints of the state’s building codes. Anthropologist Andrew Nelson [argues](https://culanth.org/fieldsights/we-need-an-even-bigger-one-disasters-of-inequality-in-postquake-kathmandu-valley) that merely reinforcing buildings will do little to mitigate the loss from future disasters without improving the socio-economic status of the Nepalese peripheral farming community.

# Crisis Hits with Bias

"Sometimes it takes a natural disaster to reveal a social disaster," [remarked](https://www.washingtonpost.com/wp-dyn/content/article/2005/09/11/AR2005091101131.html) Jim Wallis, an American theologian. The earthquake revealed another axis of discrimination: one cutting along socioreligious lines. The marginalized people of Nepal were the most severe casualty of the quake. South Asia, especially India and Nepal, have a cultural milieu of religiously-sanctioned discrimination. Nepal, though recently secular, is at best only nominally secular. Hinduism is still deeply rooted in the Nepalese psyche, and with it is inherited the ancient iron chain of caste-based stratification. The ostracized groups in the _Varna_ (caste-cluster) hierarchy, known as the “Dalits,” are labeled “untouchable” by the “higher” caste groups. The Dalits [constitute](https://idsn.org/countries/nepal/) approximately 20 percent of the Nepalese population. A former Gender, Equality, and Social Inclusion (GESI) officer at SAMATA foundation, and also a respondent of the Gorkha earthquake, Yubaraj Gajmer explained to me in person:

“Dalits like me in Nepal have confronted discrimination, expulsion, and systemic deprival of rights and inclusion from all socio-economical spheres of our lives. Following the earthquake, during my tenure with SAMATA, I was deployed in the rugged terrains of the Gorkha and Dhading hills. Disaster does hit the marginalized more severely. In the field, I’ve observed Dalits being short-changed, many had been missed-out from receiving complete relief kits, and due to illiteracy caused by systemic marginalization, many had difficulty subscribing to the government relief programs."

A [study](https://idsn.org/wp-content/uploads/2015/05/REPORT-OF-IMMEDIATE-ASSESSMENT-Relief-for-Dalits-in-NEPAL-2015.pdf) by the International Dalit Solidarity Network (IDSN) in 37 villages of the ten worst-affected districts of Nepal found that 80 percent of Dalits felt willful negligence from immediate relief support by the government. Also, 60 percent were reported to experience discrimination during the early response. The report further delineates actual narratives and testimonials from Dalit men, women, children, and elderly who were [sidelined](https://idsn.org/dalits-short-changed-in-aid-delivery-in-nepal/) to await leftover relief materials and lived in isolation, homeless, and without basic facilities.

# Oh, my beloved Dharahara!

While rural and marginalized communities felt a disproportionate impact, the capital faced other challenges. In Kathmandu, the toppling of _Dharahara,_ a 62m tall nine-storey watchtower built by then ruler Bhimsen Thapa in 1832, demonstrated this. The tower’s fall killed [180](https://earthquake.usgs.gov/learn/today/index.php?month=4&day=25) sightseers and hapless bystanders, and many more were [injured](http://archive.nepalitimes.com/article/from-nepali-press/Surviving-Dharara,2222) and impaired. However, subsequent reactions from a significant Nepali mass largely swayed to an excessive adulation of the tower, overshadowing the suffering of the victims. There were reports of people flocking the scene to pilfer and salvage the bricks from the rubbles. Others rummaged for buried artifacts in the heritage sites. Smiling blithely, even government bureaucrats among the perpetrators [reasoned](https://www.youtube.com/watch?v=HUwEn9nT3aw) that the bricks were worth collecting as antique memorabilia of the Rana kings, who ruled Nepal with an absolute iron-fist for over a century.

In the following months, locals erected idol-like [replicas](http://archive.nepalitimes.com/blogs/thebrief/2015/05/08/dhararas-replica/) for themselves, and miniature models of the tower to disperse around the country. What was left in the original site was only a stub that turned into a [selfie](https://www.washingtonpost.com/news/worldviews/wp/2015/04/27/nepals-famous-dharahara-tower-becomes-site-for-selfies-after-devastating-earthquake/) spot. While social media posts tended to emphasize a glorified Dharahara, which became emblematic of Nepal’s prospective rise from the devastation, intellectuals voicing for the marginalized underscored a rather [differing](http://archive.myrepublica.com/2015-16/opinion/story/20742/collateral-damage.html) lamentation out of the monumental loss. These zealous displays of chauvinistic hubris over a landmark were apathetic to the intrinsic value of individuals, yet they persisted in many forms hitherto. The incident also unveiled a deeper reality of the Nepalese ethos that sadly features naivety and moral insensitivity.

# Disaster as a Political Tool

The earthquake not only devastated lives and livelihoods, but it also provoked unique impacts on the international stage, especially in the realm of “disaster politics.” In the early response phase of the earthquake, India and China [competed](https://www.theguardian.com/global-development/2015/jun/25/nepal-earthquakes-3bn-aid-pledge-international-donors-kathmandu) against each other in terms of disaster aid, with India ultimately outvying its geopolitical rival, including everyone else at the donor’s table. India appears to desperately shift its stance from an aid-receiving to an aid-giving state. This attempted transition can be traced back to India’s initial [cold shoulder](https://www.nytimes.com/2005/10/19/world/asia/pride-and-politics-india-rejects-quake-aid.html) to foreign aid during its 2004 tsunami crisis, attempting to project a self-reliant image to the global community. However, India’s solo attitude was quickly deflated when the joint assessment team of the World Bank, the Asian Development Bank, and the United Nations [inspected](http://news.bbc.co.uk/2/hi/asia-pacific/4369773.stm) ground zero and came up with a price tag of US\$1.2 billion for the recovery — a sum India could not afford on its own. India thus later accepted the aid.

Pamela Philipose notes another facet of disaster politics: In “[the paradox of aid-giving,](https://www.himalmag.com/everybody-loves-a-good-earthquake/)” ruling elites can sometimes displace the actual need of the vulnerable in the name of its “national interest.” For instance, the India-Pakistan acrimony took a toll on 30,000 families in the frigid hamlets after the 2005 Kashmir earthquake as New Delhi [called off](https://www.nytimes.com/2005/10/19/world/asia/pride-and-politics-india-rejects-quake-aid.html) all foreign aid. The paradox loomed again in the aftermath of the Gorkha earthquake when essential goods such as daily commodities, fuel, and medicines previously imported from India were blocked. Initially, as discussed above, India competed to be the most generous supporter, but then contradicted its stance when it sealed off the India-Nepal ports. Before the dust of the quake settled, Nepal, which relies mainly on Indian imports, was hit with a double blow with the [imposition of the blockade](https://www.nepjol.info/index.php/rnjds/article/view/21270) that lasted for four months. The blockade was orchestrated by the South Block in the cover of the Madhesi agitation, for its grudge over the then promulgated Constitution of Nepal, which India denies. A fact-finding [mission](http://www.southasianrights.org/wp-content/uploads/2016/06/Report-on-the-Fact-Finding-Mission-to-Nepal.pdf) by South Asians for Human Rights (SAHR) concluded that the blockade exacerbated the Gorkha earthquake’s humanitarian toll.

Preceding the flagrant blockade, the Indian media, on the other hand, took an onslaught of [backlash](https://www.bbc.com/news/world-asia-india-32579561) in Nepal’s social media space, mainly for its shrillness and insensitivity towards the victims of the quake. Sensationalism and jingoism have long plagued the Indian media. Anyone stumbling upon an Indian news program is inundated with flashy graphics, dramatic sound effects, and frenzied polemic. The media of the Bollywood-doting nation deliberately displaces what would rather be a solemn discourse. In galore is a grotesque form of what Usha Rodriguez [observes](https://books.google.com.np/books?id=2RqJCwAAQBAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=snippet&q=tending%20towards%20'infotainment'&f=false) as “infotainment.” In the Gorkha earthquake, Indian journalism went beyond the substandard to being outright unethical. Media coverage primarily glorified Indian efforts. Simultaneously, Pakistan was incessantly henpecked for distributing ready-to-eat meals with beef seasonings in “Hindu Nepal.”

# Farewell to Chinook

Another episode on the international front concerns the Nepalese government’s decision to [avert](https://www.theguardian.com/uk-news/2015/may/15/raf-chinooks-recalled-from-nepal-quake-effort-without-flying-a-mission) the British Chinooks. Initially, the decision hampered the British government’s rescue [efforts](https://www.gov.uk/government/news/uk-government-deploys-chinook-helicopters-to-nepal) in ferrying emergency supplies to the remote terrains. The official Nepalese statement attempted to justify the move by [citing](https://www.independent.co.uk/news/uk/home-news/nepal-earthquake-british-chinooks-banned-from-delivering-aid-in-case-they-blow-roofs-off-10246876.html) the structural damage that could be triggered by the helicopter’s high-caliber tandem rotors. Diplomatic experts [suggested](https://www.amnestyusa.org/files/p4583_report_-_nepal_report_on_earthquake_web.pdf_-_adobe_acrobat_pro_0.pdf) otherwise, arguing that the decision symbolized resentment towards the British authorities’ earlier decision to prosecute a Nepalese army officer residing in the UK for inflicting torture during the Maoist-led civil war. Optimally, the government would have tactfully harnessed the Chinooks while circumventing the presumed obstacles. However, it did not, and thus lost 3 million pounds (USD\$3.9 million) in British aid. More severely, the Nepalese government deprived the desperate victims of the remote hills from life-saving aid of equal monetary value. This is a stark reminder that Nepalese foreign policy must be actively checked by humanitarian ethics where all political agendas are overridden by the needs of the affected.

# Homage to the Heroes

Despite the politicking at play on the international aid front, the Gorkha earthquake, in some ways, revealed the best of humanity. Courageous rescuers, civil and military personnel, doctors, experts, bureaucrats, and humanitarians converged from all over the world in Nepal. Along with Nepali survivors, they transcended the call of duty to save lives and alleviate suffering. A portion of Nepal’s youth demonstrated a salient reorientation of their role in society. They showed collaborative altruism through self-motivated [volunteering](https://ayon.org/2016/04/25/press-release-on-the-first-anniversary-of-gorkha-earthquake-2015/). Students engaged in [innovative applications](https://www.nytimes.com/2015/06/02/opinion/shaking-up-the-status-quo-in-nepal.html) of social media and information technologies from setting-up Facebook groups, to [matching](https://archive.nepalitimes.com/article/Nepali-Times-Buzz/share-a-ride-Kathmandu,2738) medicine donors to recipients, to enumerating needs assessment in the villages with [mobile surveys](https://akvo.org/blog/assessing-damage-wash-status-in-gorkha-using-akvo-flow/).

The National Planning Commission laid the way forward for the response, rapidly accomplishing the mammoth task of conducting a Post Disaster Needs Assessment ([PDNA](https://www.worldbank.org/content/dam/Worldbank/document/SAR/nepal-pdna-executive-summary.pdf)). The assessment adhered to the [Sendai Framework](https://www.preventionweb.net/files/43291_sendaiframeworkfordrren.pdf) and commendably followed a participatory approach, identifying actual needs and providing an objective baseline for the response. Despite Nepal’s precarious terrains, and persevering through the downpour of the June to September monsoon, the state and humanitarian partners collaborated to render vital [achievements](https://reliefweb.int/report/nepal/nepal-earthquake-humanitarian-response-april-september-2015). Consequently, over 3 million beneficiaries received immediate shelter support, 300 thousand children received psychosocial care and safe learning spaces, 2.6 million benefited from water, sanitation, and hygiene (WASH) provisions, and 100 percent of the damaged health facilities were in operation again by September. Three-quarters of affected households were reported to be rebuilt last year, and the government has [initiated](https://kathmandupost.com/miscellaneous/2018/03/27/govt-plans-to-retrofit-houses-in-one-year) a retrofitting program for all affected houses across Nepal.

# Strengthened Preparedness

Many scholars and policymakers focus on diplomacy, international trade, and national security with [little regard](https://www.ibei.org/en/the-politics-and-practice-of-international-humanitarianism_31319) to their interaction with humanitarian efforts. In Nepal, this inclination is carried onto its foreign policy that puts much [emphasis](https://www.nepjol.info/index.php/JPS/article/view/20437) on maintaining a balanced relationship (what it tags as ‘equi-proximity and non-alignment’ principles) between foreign partners, especially between its neighbors, India and China. However, the Gorkha earthquake has rendered additional dynamics and an urgency to eliminate threats to humanitarian efforts involving foreign stakeholders. As evidenced above in the discussions of disaster diplomacy, it is high time that the government of Nepal look into establishing a dedicated think tank that can produce incisive analyses for subtle maneuvering to wrangle the vested interest of foreign stakeholders while expunging its own. The intellectual bodies must inform Nepalese foreign policy to discern altruism-clad aid from national interests, thus mitigating the potential for subtle exploitation of disaster scenarios. Furthermore, it must strive to entirely detach aid handling over any political rancors. Meanwhile, Indian journalism should protect its ethical integrity in general and uphold compassion towards the victims it reports about, in particular. Finally, the Nepalese mass must probe its own worldview vis-à-vis equality and human rights while cultivating a culture of benevolence and critical thought.

Concerning institutional aspects, for starters, minimal humanitarian standards akin to the [Humanitarian Accountability Partnership (HAP)](https://reliefweb.int/report/world/guide-hap-standard-humanitarian-accountability-and-quality-management-0) and the [Sphere](https://spherestandards.org/handbook-2018/) guidelines can be extended for adaptation from the confines of aid agencies onto the federal instruments. Federalism has given a favorable opportunity to build back better. Exercising greater autonomy, the subnational authorities must fine-tune their programs employing participatory capacity assessment and vulnerability mapping, a resolute human rights-based approach, and continual inclusion monitoring and evaluation. There must be periodic dialogues among communal stakeholders such as the civil-police, and the public-private. Meticulous audits of social equity must also commence in the communities.

The overarching priority for all humanitarian responses must be morality first, reflected in an undivided focus on alleviating human suffering, protecting the dignity of victims, and collaboratively promoting human welfare.

_The views expressed in this article are the author's own; they do not represent the institutions of his past or present affiliations._

**Originally published in the [Harvard International Review](https://hir.harvard.edu/gorkha-earthquake/).**
