backend:
  name: github
  repo: BijuAle/BijuAle.github.io
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "blog"
    description: "My Blog Posts"
    folder: "src/posts"
    editor:
      preview: true
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
        }
      - { label: "Body", name: "body", widget: "markdown" }
